[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://your-backend-url.herokuapp.com"
  VITE_SOCKET_URL = "https://your-backend-url.herokuapp.com"

[context.deploy-preview.environment]
  VITE_API_URL = "https://your-backend-url.herokuapp.com"
  VITE_SOCKET_URL = "https://your-backend-url.herokuapp.com"
