services:
  - type: web
    name: project-management-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: project-management-db
          property: connectionString
      - key: JWT_SECRET
        value: Shakushaku1
      - key: JWT_EXPIRE
        value: 30d
      - key: CLIENT_URL
        value: https://product-management-tool.netlify.app
      - key: PORT
        value: 10000

databases:
  - name: project-management-db
    databaseName: project_management_db
    user: postgres
    region: oregon
    plan: free
