services:
  - type: web
    name: project-management-backend
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: project-management-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: CLIENT_URL
        value: https://your-frontend-url.netlify.app

databases:
  - name: project-management-db
    databaseName: project_management_db
    user: postgres
